[package]
name = "bible-presenter-rs"
version = "1.2.3"
description = "A professional, real-time Bible projection tool for churches."
authors = ["Bible Presenter Team"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = ["protocol-asset"] }
tauri-plugin-shell = "2.0.0"
tauri-plugin-fs = "2.0.0"
tauri-plugin-dialog = "2.0.0"
uuid = { version = "1", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
whisper-rs = "0.12.0" 
cpal = "0.15.3"      
rusqlite = { version = "0.31.0", features = ["bundled-full"] }
rubato = "0.14"      # High-quality resampling
tokenizers = "0.19"
ort = "2.0.0-rc.11"
ndarray = "0.15"     # Tensor manipulation
ndarray-npy = "0.8"  # Load .npy files
hnsw_rs = "0.3.4"
memmap2 = "0.9"
anyhow = "1.0"        
parking_lot = "0.12" 
regex = "1.10"       
image = "0.25"
num_cpus = "=1.16.0"
base64 = "0.22"
once_cell = "1"
axum = { version = "0.7", features = ["ws"] }
tower-http = { version = "0.5", features = ["cors"] }
local-ip-address = "0.1"
rand = "0.8"
futures-util = "0.3"
reqwest  = { version = "0.12", features = ["json", "stream", "rustls-tls", "multipart"], default-features = false }
sysinfo  = { version = "0.30", default-features = false }
webrtc-vad = "0.4.0"
ringbuf = "0.4.8"
tokio-tungstenite = { version = "0.24", features = ["rustls-tls-webpki-roots"], default-features = false }
chrono = { version = "0.4", features = ["serde"] }

[lib]
name = "bible_presenter_lib"
crate-type = ["rlib"]

[[bin]]
name = "bible-presenter"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = "s" # Optimize for size
strip = true    # Automatically strip symbols from the binary
